AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Project Portal - Secrets Manager
  Auth0 credentials for frontend and backend services

Parameters:
  Environment:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - prod
    Description: Deployment environment

Resources:
  Auth0FrontendSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub 'portal-${Environment}/auth0-frontend'
      Description: !Sub >
        Auth0 frontend credentials for ${Environment}.
        Required keys: AUTH0_SECRET, AUTH0_CLIENT_ID, AUTH0_CLIENT_SECRET.
        Populate after initial deploy via:
        aws secretsmanager put-secret-value --secret-id portal-${Environment}/auth0-frontend --secret-string '{"AUTH0_SECRET":"...","AUTH0_CLIENT_ID":"...","AUTH0_CLIENT_SECRET":"..."}'
      SecretString: '{"AUTH0_SECRET":"PLACEHOLDER_REPLACE_ME","AUTH0_CLIENT_ID":"PLACEHOLDER_REPLACE_ME","AUTH0_CLIENT_SECRET":"PLACEHOLDER_REPLACE_ME"}'

  Auth0BackendSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub 'portal-${Environment}/auth0-backend'
      Description: !Sub >
        Auth0 backend credentials for ${Environment}.
        Required keys: AUTH0_DOMAIN, AUTH0_AUDIENCE.
        Populate after initial deploy via:
        aws secretsmanager put-secret-value --secret-id portal-${Environment}/auth0-backend --secret-string '{"AUTH0_DOMAIN":"...","AUTH0_AUDIENCE":"..."}'
      SecretString: '{"AUTH0_DOMAIN":"PLACEHOLDER_REPLACE_ME","AUTH0_AUDIENCE":"PLACEHOLDER_REPLACE_ME"}'

Outputs:
  Auth0FrontendSecretArn:
    Description: ARN of the frontend Auth0 secret
    Value: !Ref Auth0FrontendSecret
    Export:
      Name: !Sub '${AWS::StackName}-Auth0FrontendSecretArn'

  Auth0BackendSecretArn:
    Description: ARN of the backend Auth0 secret
    Value: !Ref Auth0BackendSecret
    Export:
      Name: !Sub '${AWS::StackName}-Auth0BackendSecretArn'

  Auth0FrontendSecretName:
    Description: Name of the frontend Auth0 secret
    Value: !Sub 'portal-${Environment}/auth0-frontend'

  Auth0BackendSecretName:
    Description: Name of the backend Auth0 secret
    Value: !Sub 'portal-${Environment}/auth0-backend'
