AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Project Portal - Secrets Manager
  Auth0 credentials and database password for frontend and backend services

Parameters:
  Environment:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - prod
    Description: Deployment environment

  ClientName:
    Type: String
    Description: Client short name (e.g., turbotech, fpls)

  ProjectName:
    Type: String
    Description: Project short name (e.g., portal, boss)

Resources:
  Auth0FrontendSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub '${ClientName}-${Environment}-${ProjectName}/auth0-frontend'
      Description: !Sub >
        Auth0 frontend credentials for ${Environment}.
        Required keys: AUTH0_SECRET, AUTH0_CLIENT_ID, AUTH0_CLIENT_SECRET.
        Populate after initial deploy via:
        aws secretsmanager put-secret-value --secret-id ${ClientName}-${Environment}-${ProjectName}/auth0-frontend --secret-string '{"AUTH0_SECRET":"...","AUTH0_CLIENT_ID":"...","AUTH0_CLIENT_SECRET":"..."}'
      SecretString: '{"AUTH0_SECRET":"PLACEHOLDER_REPLACE_ME","AUTH0_CLIENT_ID":"PLACEHOLDER_REPLACE_ME","AUTH0_CLIENT_SECRET":"PLACEHOLDER_REPLACE_ME"}'

  Auth0BackendSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub '${ClientName}-${Environment}-${ProjectName}/auth0-backend'
      Description: !Sub >
        Auth0 backend credentials for ${Environment}.
        Required keys: AUTH0_DOMAIN, AUTH0_AUDIENCE, AUTH0_ORGANIZATION.
        Populate after initial deploy via:
        aws secretsmanager put-secret-value --secret-id ${ClientName}-${Environment}-${ProjectName}/auth0-backend --secret-string '{"AUTH0_DOMAIN":"...","AUTH0_AUDIENCE":"...","AUTH0_ORGANIZATION":"..."}'
      SecretString: '{"AUTH0_DOMAIN":"PLACEHOLDER_REPLACE_ME","AUTH0_AUDIENCE":"PLACEHOLDER_REPLACE_ME"}'

  DatabaseSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub '${ClientName}-${Environment}-${ProjectName}/database'
      Description: !Sub >
        Database credentials for ${Environment}.
        Required keys: DB_PASSWORD.
        Populate after initial deploy via:
        aws secretsmanager put-secret-value --secret-id ${ClientName}-${Environment}-${ProjectName}/database --secret-string '{"DB_PASSWORD":"<strong-password>"}'
      SecretString: '{"DB_PASSWORD":"PLACEHOLDER_REPLACE_ME"}'

Outputs:
  Auth0FrontendSecretArn:
    Description: ARN of the frontend Auth0 secret
    Value: !Ref Auth0FrontendSecret
    Export:
      Name: !Sub '${AWS::StackName}-Auth0FrontendSecretArn'

  Auth0BackendSecretArn:
    Description: ARN of the backend Auth0 secret
    Value: !Ref Auth0BackendSecret
    Export:
      Name: !Sub '${AWS::StackName}-Auth0BackendSecretArn'

  DatabaseSecretArn:
    Description: ARN of the database secret
    Value: !Ref DatabaseSecret
    Export:
      Name: !Sub '${AWS::StackName}-DatabaseSecretArn'

  Auth0FrontendSecretName:
    Description: Name of the frontend Auth0 secret
    Value: !Sub '${ClientName}-${Environment}-${ProjectName}/auth0-frontend'

  Auth0BackendSecretName:
    Description: Name of the backend Auth0 secret
    Value: !Sub '${ClientName}-${Environment}-${ProjectName}/auth0-backend'

  DatabaseSecretName:
    Description: Name of the database secret
    Value: !Sub '${ClientName}-${Environment}-${ProjectName}/database'
